/**
 * Merkle byte-equality test.
 *
 * Asserts that the TypeScript port in `lib/merkle.ts` produces byte-identical
 * hashes to the Rust reference impl in `genesis/src/merkle.rs` and the
 * inclusion-proof construction in `tools/claim-cli/src/proof.rs`.
 *
 * Fixtures were generated by a small Rust program against the actual reference
 * crates and pinned here as hex strings. See the comment header below for the
 * exact source. To regenerate after a Rust-side change, see the README.
 */

import { PublicKey } from "@solana/web3.js";
import { describe, expect, it } from "vitest";

import {
  bitIsSet,
  buildInclusionProof,
  buildMerkleRoot,
  leafHash,
  packBits,
  recomputeRoot,
  toHex,
  type ClaimableLeaf,
} from "@/lib/merkle";

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

function pk(byte: number): PublicKey {
  return new PublicKey(new Uint8Array(32).fill(byte));
}

function leaf(byte: number, lamports: bigint): ClaimableLeaf {
  return { pubkey: pk(byte), lamports };
}

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

// Roots produced by `staccana_genesis::merkle::MerkleTree::build` against the
// indicated leaf inputs. Generated 2026-05-02 from
// staccana-genesis @ workspace 0.1.0 against solana-program 2.x.
const ROOT_FIXTURES = {
  empty: "0000000000000000000000000000000000000000000000000000000000000000",
  singleLeaf7_500: "0cb57384b6253014a575f609a35403aff9fdf91d8191633aba4ad63f0cfc7d56",
  twoLeaves: "3479b96a17dceada4de7da3c06596957cbbc9bc17112f825513db67489a335c7",
  fourLeaves: "9be8014c86eaeddf4aa045d901faf07ca1de2b08348c4e6d9bf5ab707e826903",
  threeLeavesOdd: "c0ef2a01acb016588c7beb7d5ba3672e08cf681d8feabced355d1f50c3278a53",
  sevenLeaves: "90d7c8c91fbb9443a3c700b51c8252d53e840b51df4d569ae7c0365d6cb71521",
} as const;

// Leaf hashes from `ClaimableLeaf::hash`.
const LEAF_FIXTURES = {
  leaf1_1000: "7fb8a254740be5df899cec1cfae84eb9e0108fbc9da24c9df771e79eb3f7cc37",
  leaf2_2000: "1e7c77b88abe7e14f8d0cb384ff7ae3b3927e3358ee38c7c4cb615ce6deea91f",
  leaf7_500: "0cb57384b6253014a575f609a35403aff9fdf91d8191633aba4ad63f0cfc7d56",
} as const;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("merkle: leaf hashes byte-equal Rust impl", () => {
  it("leaf(1, 1000)", async () => {
    expect(toHex(await leafHash(leaf(1, 1000n)))).toBe(LEAF_FIXTURES.leaf1_1000);
  });
  it("leaf(2, 2000)", async () => {
    expect(toHex(await leafHash(leaf(2, 2000n)))).toBe(LEAF_FIXTURES.leaf2_2000);
  });
  it("leaf(7, 500)", async () => {
    expect(toHex(await leafHash(leaf(7, 500n)))).toBe(LEAF_FIXTURES.leaf7_500);
  });
});

describe("merkle: roots byte-equal Rust impl", () => {
  it("empty input → 32-byte zero hash", async () => {
    expect(toHex(await buildMerkleRoot([]))).toBe(ROOT_FIXTURES.empty);
  });

  it("single leaf → root is leaf hash", async () => {
    expect(toHex(await buildMerkleRoot([leaf(7, 500n)]))).toBe(ROOT_FIXTURES.singleLeaf7_500);
  });

  it("two leaves [pk1=100, pk2=200]", async () => {
    expect(toHex(await buildMerkleRoot([leaf(1, 100n), leaf(2, 200n)]))).toBe(ROOT_FIXTURES.twoLeaves);
  });

  it("four leaves [pk1..pk4]", async () => {
    const root = await buildMerkleRoot([
      leaf(1, 100n),
      leaf(2, 200n),
      leaf(3, 300n),
      leaf(4, 400n),
    ]);
    expect(toHex(root)).toBe(ROOT_FIXTURES.fourLeaves);
  });

  it("three leaves (odd duplication) [pk1..pk3]", async () => {
    const root = await buildMerkleRoot([leaf(1, 100n), leaf(2, 200n), leaf(3, 300n)]);
    expect(toHex(root)).toBe(ROOT_FIXTURES.threeLeavesOdd);
  });

  it("seven leaves (multiple odd reductions) [pk1..pk7]", async () => {
    const leaves: ClaimableLeaf[] = [];
    for (let i = 1; i <= 7; i++) leaves.push(leaf(i, BigInt(100 * i)));
    expect(toHex(await buildMerkleRoot(leaves))).toBe(ROOT_FIXTURES.sevenLeaves);
  });

  it("input order does not affect the root", async () => {
    const ordered = await buildMerkleRoot([
      leaf(1, 100n),
      leaf(2, 200n),
      leaf(3, 300n),
      leaf(4, 400n),
    ]);
    const shuffled = await buildMerkleRoot([
      leaf(4, 400n),
      leaf(2, 200n),
      leaf(1, 100n),
      leaf(3, 300n),
    ]);
    expect(toHex(ordered)).toBe(toHex(shuffled));
    expect(toHex(ordered)).toBe(ROOT_FIXTURES.fourLeaves);
  });
});

describe("merkle: inclusion proofs byte-equal Rust impl", () => {
  // Each fixture is a 4-tuple: (leaf set, target byte, expected proof_flags hex,
  // expected sibling hashes hex array). Generated from
  // staccana_claim_cli::proof::build_inclusion_proof.
  const FIXTURES: Array<{
    label: string;
    leaves: ClaimableLeaf[];
    targetByte: number;
    expectedRoot: string;
    expectedFlagsHex: string;
    expectedSiblingsHex: string[];
  }> = [
    // two leaves
    {
      label: "two leaves, target pk1",
      leaves: [leaf(1, 100n), leaf(2, 200n)],
      targetByte: 1,
      expectedRoot: ROOT_FIXTURES.twoLeaves,
      expectedFlagsHex: "01",
      expectedSiblingsHex: ["9e091d64e946a11b24ba07fc41cf12c8a66894a45598b74679c931f44cdf2478"],
    },
    {
      label: "two leaves, target pk2",
      leaves: [leaf(1, 100n), leaf(2, 200n)],
      targetByte: 2,
      expectedRoot: ROOT_FIXTURES.twoLeaves,
      expectedFlagsHex: "00",
      expectedSiblingsHex: ["3704030f95718ebf350aa5d54e466fa2134818d26c4267f65d70d1a7421cbcb7"],
    },

    // four leaves
    {
      label: "four leaves, target pk1",
      leaves: [leaf(1, 100n), leaf(2, 200n), leaf(3, 300n), leaf(4, 400n)],
      targetByte: 1,
      expectedRoot: ROOT_FIXTURES.fourLeaves,
      expectedFlagsHex: "03",
      expectedSiblingsHex: [
        "9e091d64e946a11b24ba07fc41cf12c8a66894a45598b74679c931f44cdf2478",
        "b4dcaad4915085900cf4f4779e4dceb0b05e60299b3eb9882730d83154da68e4",
      ],
    },
    {
      label: "four leaves, target pk2",
      leaves: [leaf(1, 100n), leaf(2, 200n), leaf(3, 300n), leaf(4, 400n)],
      targetByte: 2,
      expectedRoot: ROOT_FIXTURES.fourLeaves,
      expectedFlagsHex: "02",
      expectedSiblingsHex: [
        "3704030f95718ebf350aa5d54e466fa2134818d26c4267f65d70d1a7421cbcb7",
        "b4dcaad4915085900cf4f4779e4dceb0b05e60299b3eb9882730d83154da68e4",
      ],
    },
    {
      label: "four leaves, target pk3",
      leaves: [leaf(1, 100n), leaf(2, 200n), leaf(3, 300n), leaf(4, 400n)],
      targetByte: 3,
      expectedRoot: ROOT_FIXTURES.fourLeaves,
      expectedFlagsHex: "01",
      expectedSiblingsHex: [
        "c985eff98bfcc451669073006ea01f24569756e84210b3340889e1160f3197ca",
        "3479b96a17dceada4de7da3c06596957cbbc9bc17112f825513db67489a335c7",
      ],
    },
    {
      label: "four leaves, target pk4",
      leaves: [leaf(1, 100n), leaf(2, 200n), leaf(3, 300n), leaf(4, 400n)],
      targetByte: 4,
      expectedRoot: ROOT_FIXTURES.fourLeaves,
      expectedFlagsHex: "00",
      expectedSiblingsHex: [
        "ca08e03b71dc8792c1a5848bb06ddc7f3b0d8775ba95af7e52267df4137074c3",
        "3479b96a17dceada4de7da3c06596957cbbc9bc17112f825513db67489a335c7",
      ],
    },

    // three leaves (odd)
    {
      label: "three leaves (odd), target pk3 (the odd one)",
      leaves: [leaf(1, 100n), leaf(2, 200n), leaf(3, 300n)],
      targetByte: 3,
      expectedRoot: ROOT_FIXTURES.threeLeavesOdd,
      expectedFlagsHex: "01",
      expectedSiblingsHex: [
        "ca08e03b71dc8792c1a5848bb06ddc7f3b0d8775ba95af7e52267df4137074c3",
        "3479b96a17dceada4de7da3c06596957cbbc9bc17112f825513db67489a335c7",
      ],
    },

    // seven leaves (multi-level odd)
    {
      label: "seven leaves, target pk7 (odd at every reduction)",
      leaves: (() => {
        const ls: ClaimableLeaf[] = [];
        for (let i = 1; i <= 7; i++) ls.push(leaf(i, BigInt(100 * i)));
        return ls;
      })(),
      targetByte: 7,
      expectedRoot: ROOT_FIXTURES.sevenLeaves,
      expectedFlagsHex: "01",
      expectedSiblingsHex: [
        "c34dba36ff3716b8d7ee1e24b7f28be4d19d5dcf8e5cc58a2528a1af502c9ae1",
        "ce78c8f31effc2fb69530d8175a306758bfe7eb16e0b6ff208918679f05f5d01",
        "9be8014c86eaeddf4aa045d901faf07ca1de2b08348c4e6d9bf5ab707e826903",
      ],
    },
  ];

  for (const f of FIXTURES) {
    it(f.label, async () => {
      const proof = await buildInclusionProof(f.leaves, pk(f.targetByte));
      expect(proof).not.toBeNull();
      const p = proof!;
      expect(toHex(p.root)).toBe(f.expectedRoot);
      expect(p.proof.length).toBe(f.expectedSiblingsHex.length);
      for (let i = 0; i < p.proof.length; i++) {
        expect(toHex(p.proof[i])).toBe(f.expectedSiblingsHex[i]);
      }
      expect(toHex(p.proofFlags)).toBe(f.expectedFlagsHex);
      // Self-check: recomputed root matches.
      expect(toHex(await recomputeRoot(p))).toBe(f.expectedRoot);
    });
  }

  it("returns null when target is not in the leaf set", async () => {
    const proof = await buildInclusionProof([leaf(1, 100n), leaf(2, 200n)], pk(42));
    expect(proof).toBeNull();
  });

  it("single-leaf tree → empty proof, root = leaf hash", async () => {
    const ls = [leaf(7, 500n)];
    const proof = await buildInclusionProof(ls, pk(7));
    expect(proof).not.toBeNull();
    const p = proof!;
    expect(p.proof.length).toBe(0);
    expect(p.proofFlags.length).toBe(0);
    expect(toHex(p.root)).toBe(ROOT_FIXTURES.singleLeaf7_500);
  });
});

describe("merkle: bit packing helpers", () => {
  it("pack and read bits round-trip", () => {
    const bits = [true, false, true, true, false, false, false, true, true];
    const packed = packBits(bits);
    expect(packed.length).toBe(2); // ceil(9/8)
    for (let i = 0; i < bits.length; i++) {
      expect(bitIsSet(packed, i)).toBe(bits[i]);
    }
  });

  it("matches Rust pack_bits LSB-first byte ordering", () => {
    // 9 bits: [1,0,1,1,0,0,0,1,1] → byte 0 = 0b10001101 = 0x8d, byte 1 = 0b1 = 0x01
    const packed = packBits([true, false, true, true, false, false, false, true, true]);
    expect(toHex(packed)).toBe("8d01");
  });
});

describe("merkle: fromHex helper sanity", () => {
  it("round-trips toHex", () => {
    const bytes = new Uint8Array([0x00, 0x01, 0xff, 0xab]);
    expect(toHex(bytes)).toBe("0001ffab");
    expect(Array.from(fromHex("0001ffab"))).toEqual([0x00, 0x01, 0xff, 0xab]);
  });
});
